# Lists and Tuples <hr style="border:2px solid #ff0000 "><hr>

<b> Rex Orly Mallorca </b>
<br> CompTech Student

In [71]:
#importing and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [65]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [66]:
np.shape(my_array)

(3,)

# 2D Array

In [25]:
my_array = np.array([[1,2,3], 
                     [4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.shape(my_array)

(2, 3)

In [27]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
np.shape(t_array)

(3, 2)

# Measures of Central Tendency

In [32]:
#Jaguar vs Panther
resistance =  np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])

resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [33]:
np.shape(resistance)

(2, 11)

In [67]:
#Mean
res_mean = np.nanmean(resistance,axis=1)
res_mean[0]

np.float64(9.399999999999999)

In [79]:
print("Jaguar Mean: " + str((res_mean[0]).round(2)) + " Ω")

Jaguar Mean: 9.4 Ω


In [80]:
print(f'Jaguar: {res_mean[0]:.2f} Ω')
print(f'Panther: {res_mean[1]:.2f} Ω')

Jaguar: 9.40 Ω
Panther: 10.75 Ω


In [81]:
#Median
res_median = np.nanmedian(resistance,axis=1)
res_median[0]

np.float64(9.8)

In [82]:
print(f'Jaguar: {res_median[0]:.2f} Ω')
print(f'Panther: {res_median[1]:.2f} Ω')

Jaguar: 9.80 Ω
Panther: 9.55 Ω


In [83]:
res_mode = stats.mode(resistance, axis=1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [84]:
jag_res = resistance[0]

print("Jaguar Mode: ")
for i in multimode(jag_res):
    print(f'{i} Ω')

Jaguar Mode: 
9.8 Ω
10.4 Ω


In [87]:
pan_res = resistance[1]

print("Panther Mode: ")
for i in multimode(pan_res):
    print(f'{i} Ω')

Panther Mode: 
9.1 Ω


In [88]:
#Jaguar vs Panther
resistance =  np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])

resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [91]:
#Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [92]:
print(f'Jaguar: {res_range[0]:.2f} Ω')
print(f'Panther: {res_range[1]:.2f} Ω')

Jaguar: 8.00 Ω
Panther: 10.90 Ω


In [ ]:
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1


array([9.4  , 9.125])

In [95]:
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [98]:
print(f'Jaguar IQR:  {res_Q3[0] - res_Q1[0]: .2f} Ω')
print(f'Panther IQR:  {res_Q3[1] - res_Q1[1]: .2f} Ω')

Jaguar IQR:   1.05 Ω
Panther IQR:   1.50 Ω


In [102]:
res_var = np.nanvar(resistance, ddof =1,axis=1)

print(f'Jaguar Variance:  {res_var[0]:.2f} Ω')
print(f'Panther Variance:  {res_var[1]:.2f} Ω')

Jaguar Variance:  4.86 Ω
Panther Variance:  11.08 Ω


In [103]:
res_std = np.nanstd(resistance, ddof =1,axis=1)

print(f'Jaguar Variance:  {res_std[0]:.2f} Ω')
print(f'Panther Variance:  {res_std[1]:.2f} Ω')

Jaguar Variance:  2.20 Ω
Panther Variance:  3.33 Ω
